import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MiniCard } from "../../components/mini-card/mini-card";

@Component({
  selector: 'app-profile-list',
  imports: [MiniCard, CommonModule],
  templateUrl: './profile-list.html',
  styleUrl: './profile-list.css'
})
export class ProfileList {

  itens = [
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "3.700,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "70,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "0,99",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "3.700,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "70,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "0,99",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "3.700,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "70,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "0,99",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        },
        {src: "assets/images/produto-teste.png",
         title: "Fone de Ouvido Headset",
         price: "1.500,25",
         currency: "R$",
         extclass: "itens-class",
         fullinfo: true,
         href: "/product?category=1&subcategory=3"
        }
      ];
}
